#!/bin/bash

# 2FA Email Configuration Setup Script
# This script helps set up SendGrid SMTP for 2FA emails

set -e

echo "======================================"
echo "MDD Management System - 2FA Setup"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if .env file exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}ℹ️  .env file already exists${NC}"
    read -p "Do you want to update it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo "Please provide your SendGrid SMTP configuration:"
echo ""

# Get SMTP host
read -p "Email Host (default: smtp.sendgrid.net): " EMAIL_HOST
EMAIL_HOST=${EMAIL_HOST:-smtp.sendgrid.net}

# Get SMTP port
read -p "Email Port (default: 587): " EMAIL_PORT
EMAIL_PORT=${EMAIL_PORT:-587}

# Get SMTP username
read -p "Email Username (default: apikey): " EMAIL_HOST_USER
EMAIL_HOST_USER=${EMAIL_HOST_USER:-apikey}

# Get SMTP password
echo "Enter your SendGrid API Key (or press Ctrl+C to cancel):"
read -s EMAIL_HOST_PASSWORD

# Get from email
read -p "Default From Email: " DEFAULT_FROM_EMAIL

if [ -z "$DEFAULT_FROM_EMAIL" ]; then
    echo -e "${RED}Error: From email is required${NC}"
    exit 1
fi

# Create or update .env file
cat > .env << EOF
# Email Configuration for 2FA via SendGrid SMTP
# Generated by setup script

EMAIL_HOST=$EMAIL_HOST
EMAIL_PORT=$EMAIL_PORT
EMAIL_HOST_USER=$EMAIL_HOST_USER
EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
EOF

chmod 600 .env  # Restrict file permissions

echo ""
echo -e "${GREEN}✓ .env file created successfully${NC}"
echo ""

# Create directory for admin utilities if it doesn't exist
if [ ! -d "public/admin" ]; then
    mkdir -p public/admin
    echo -e "${GREEN}✓ Created public/admin directory${NC}"
fi

echo ""
echo "======================================"
echo "Configuration Summary:"
echo "======================================"
echo "SMTP Host:        $EMAIL_HOST"
echo "SMTP Port:        $EMAIL_PORT"
echo "Username:         $EMAIL_HOST_USER"
echo "Password:         ${EMAIL_HOST_PASSWORD:0:8}...${EMAIL_HOST_PASSWORD: -4}"
echo "From Email:       $DEFAULT_FROM_EMAIL"
echo ""
echo "======================================"
echo ""

# Test the configuration
read -p "Do you want to test the email configuration now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    php -r "
        require_once 'includes/config.php';
        require_once 'includes/email.php';
        
        \$results = test_email_configuration();
        
        echo \"\\n\";
        if (\$results['success']) {
            echo \"✓ Email configuration is valid\\n\";
        } else {
            echo \"✗ Email configuration has issues:\\n\";
        }
        
        foreach (\$results['messages'] as \$msg) {
            echo \"  - \$msg\\n\";
        }
        echo \"\\n\";
    "
else
    echo "Skipped email configuration test."
fi

echo "======================================"
echo "Setup complete!"
echo "======================================"
echo ""
echo "Next steps:"
echo "1. Visit http://localhost:8000/admin/email-test.php to test sending"
echo "2. Try logging in at http://localhost:8000/login.php"
echo "3. Check your email for the verification code"
echo ""
echo "Documentation: See 2FA_IMPLEMENTATION.md"
echo ""
