# 2FA Email Configuration Setup Script (PowerShell)
# This script helps set up SendGrid SMTP for 2FA emails on Windows

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "MDD Management System - 2FA Setup" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

$envFile = ".env"

# Check if .env file exists
if (Test-Path $envFile) {
    Write-Host "ℹ️  .env file already exists" -ForegroundColor Yellow
    $update = Read-Host "Do you want to update it? (y/n)"
    if ($update -ne 'y' -and $update -ne 'Y') {
        Write-Host "Setup cancelled."
        exit 0
    }
}

Write-Host "Please provide your SendGrid SMTP configuration:" -ForegroundColor Green
Write-Host ""

# Get SMTP host
$emailHost = Read-Host "Email Host (default: smtp.sendgrid.net)"
if ([string]::IsNullOrWhiteSpace($emailHost)) {
    $emailHost = "smtp.sendgrid.net"
}

# Get SMTP port
$emailPort = Read-Host "Email Port (default: 587)"
if ([string]::IsNullOrWhiteSpace($emailPort)) {
    $emailPort = "587"
}

# Get SMTP username
$emailHostUser = Read-Host "Email Username (default: apikey)"
if ([string]::IsNullOrWhiteSpace($emailHostUser)) {
    $emailHostUser = "apikey"
}

# Get SMTP password (secure input)
Write-Host "Enter your SendGrid API Key:" -ForegroundColor Yellow
$securePassword = Read-Host -AsSecureString
$emailHostPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToCoTaskMemUnicode($securePassword))

# Get from email
$defaultFromEmail = Read-Host "Default From Email"

if ([string]::IsNullOrWhiteSpace($defaultFromEmail)) {
    Write-Host "Error: From email is required" -ForegroundColor Red
    exit 1
}

# Create or update .env file
$envContent = @"
# Email Configuration for 2FA via SendGrid SMTP
# Generated by setup script

EMAIL_HOST=$emailHost
EMAIL_PORT=$emailPort
EMAIL_HOST_USER=$emailHostUser
EMAIL_HOST_PASSWORD=$emailHostPassword
DEFAULT_FROM_EMAIL=$defaultFromEmail
"@

Set-Content -Path $envFile -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "✓ .env file created successfully" -ForegroundColor Green
Write-Host ""

# Create directory for admin utilities if it doesn't exist
$adminDir = "public/admin"
if (-not (Test-Path $adminDir)) {
    New-Item -ItemType Directory -Path $adminDir -Force | Out-Null
    Write-Host "✓ Created $adminDir directory" -ForegroundColor Green
}

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Configuration Summary:" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "SMTP Host:        $emailHost"
Write-Host "SMTP Port:        $emailPort"
Write-Host "Username:         $emailHostUser"
Write-Host "Password:         $($emailHostPassword.Substring(0, [Math]::Min(8, $emailHostPassword.Length)))...$(if ($emailHostPassword.Length -gt 4) { $emailHostPassword.Substring($emailHostPassword.Length - 4) })"
Write-Host "From Email:       $defaultFromEmail"
Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Test the configuration
$testChoice = Read-Host "Do you want to test the email configuration now? (y/n)"
if ($testChoice -eq 'y' -or $testChoice -eq 'Y') {
    Write-Host ""
    Write-Host "Testing email configuration..." -ForegroundColor Yellow
    Write-Host ""
    
    $testCode = @'
<?php
require_once 'includes/config.php';
require_once 'includes/email.php';

$results = test_email_configuration();

echo "\n";
if ($results['success']) {
    echo "✓ Email configuration is valid\n";
} else {
    echo "✗ Email configuration has issues:\n";
}

foreach ($results['messages'] as $msg) {
    echo "  - $msg\n";
}
echo "\n";
?>
'@
    
    $tempFile = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), "test_email_config.php")
    Set-Content -Path $tempFile -Value $testCode -Encoding UTF8
    
    try {
        & php -r "require '$tempFile';" 2>$null
    }
    catch {
        Write-Host "Note: PHP not in PATH or error running test. You can test manually later." -ForegroundColor Yellow
    }
    finally {
        Remove-Item -Path $tempFile -Force -ErrorAction SilentlyContinue
    }
}
else {
    Write-Host "Skipped email configuration test."
}

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Green
Write-Host "1. Start the development server: .\start-server.bat"
Write-Host "2. Visit http://localhost:8000/admin/email-test.php to test sending"
Write-Host "3. Try logging in at http://localhost:8000/login.php"
Write-Host "4. Check your email for the verification code"
Write-Host ""
Write-Host "Documentation: See 2FA_IMPLEMENTATION.md" -ForegroundColor Cyan
Write-Host ""
