<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';

$user = require_login();
$pdo = db();

$type = $_GET['type'] ?? 'csv'; // csv | html
$leaveType = $_GET['leave_type'] ?? '';
$dateFrom = $_GET['from'] ?? '';
$dateTo = $_GET['to'] ?? '';

// Scope to the same visibility rules as leave-requests.php
$where = '1=1';
$params = [];
if (is_manager($user)) {
    $where .= ' AND lr.branch_id = ?';
    $params[] = $user['branch_id'];
} elseif (is_officer($user)) {
    $where .= ' AND lr.submitted_by = ?';
    $params[] = $user['id'];
}

if (!empty($leaveType)) {
    $where .= ' AND lr.leave_type = ?';
    $params[] = $leaveType;
}

if (!empty($dateFrom)) {
    $where .= ' AND lr.start_date >= ?';
    $params[] = $dateFrom;
}
if (!empty($dateTo)) {
    $where .= ' AND lr.end_date <= ?';
    $params[] = $dateTo;
}

$sql = "SELECT lr.*, e.full_name AS emp_name, e.service_no, b.name AS branch_name,
              s.full_name AS submitter, m.full_name AS mgr_name, a.full_name AS adm_name
        FROM leave_requests lr
        JOIN employees e ON e.id=lr.employee_id
        JOIN branches b ON b.id=lr.branch_id
        LEFT JOIN users s ON s.id=lr.submitted_by
        LEFT JOIN users m ON m.id=lr.manager_reviewed_by
        LEFT JOIN users a ON a.id=lr.admin_reviewed_by
        WHERE $where
        ORDER BY lr.submitted_at DESC";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$requests = $stmt->fetchAll();

$label = !empty($leaveType) ? $leaveType : 'All';
$baseName = 'UPF_MDD_Leave_' . preg_replace('/[^A-Za-z0-9_-]+/', '_', (string)$label) . '_' . date('Y-m-d');

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $baseName . '.csv"');
    $out = fopen('php://output', 'w');

    fputcsv($out, [APP_ORG]);
    fputcsv($out, [APP_NAME]);
    fputcsv($out, ['Leave Export — ' . $label]);
    fputcsv($out, ['Generated by: ' . ($user['full_name'] ?? 'user') . ' on ' . date('Y-m-d H:i')]);
    fputcsv($out, []);

    fputcsv($out, ['Employee','Service No','Branch','Leave Type','Start Date','End Date','Destination','Reason','Status','Submitted By','Submitted At','Manager Review','Admin Review']);

    foreach ($requests as $r) {
        fputcsv($out, [
            $r['emp_name'],
            $r['service_no'],
            $r['branch_name'],
            $r['leave_type'],
            $r['start_date'],
            $r['end_date'],
            $r['destination'] ?? '',
            $r['reason'] ?? '',
            $r['status'],
            $r['submitter'] ?? '',
            $r['submitted_at'],
            $r['mgr_name'] ?? '',
            $r['adm_name'] ?? ''
        ]);
    }

    fclose($out);
    exit;
}

$logoPath = BASE_PATH . '/public/assets/logo.jpg';
$logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : '';
?>
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title><?= e('UPF MDD — Leave Export — ' . $label) ?></title>
  <style>
    body{font-family:Arial,sans-serif;color:#1a2236;margin:30px}
    .head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #d4a017;padding-bottom:12px;margin-bottom:18px}
    .head img{width:70px;height:70px;border-radius:50%;border:2px solid #d4a017}
    .org{font-weight:700;letter-spacing:1px;color:#0d1629}
    .sys{font-size:13px;color:#475569}
    table{width:100%;border-collapse:collapse;margin-top:14px}
    th,td{border:1px solid #cbd5e1;padding:8px 10px;font-size:12px;text-align:left;vertical-align:top}
    th{background:#0d1629;color:#fff}
    .meta{color:#64748b;font-size:12px;margin-bottom:10px}
    .no-print{margin-top:18px}
    @media print { .no-print{display:none} }
  </style>
</head>
<body>
  <div class="head">
    <?php if ($logoData): ?><img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF"><?php endif; ?>
    <div>
      <div class="org"><?= e(APP_ORG) ?></div>
      <div class="sys"><?= e(APP_NAME) ?></div>
      <div class="motto"><?= e(APP_MOTTO) ?></div>
    </div>
  </div>

  <h2 style="margin:0">Leave Export — <?= e($label) ?></h2>
  <div class="meta">Generated by <?= e($user['full_name'] ?? 'user') ?> on <?= date('j F Y H:i') ?></div>

  <table>
    <thead>
      <tr>
        <th>Employee</th><th>Service No</th><th>Branch</th><th>Leave Type</th><th>Start</th><th>End</th><th>Destination</th><th>Reason</th><th>Status</th><th>Submitted By</th><th>Submitted At</th><th>Manager</th><th>HQ</th>
      </tr>
    </thead>
    <tbody>
      <?php if (!$requests): ?>
        <tr><td colspan="13" style="text-align:center;color:#64748b">No leave requests found.</td></tr>
      <?php else: foreach ($requests as $r): ?>
        <tr>
          <td><?= e($r['emp_name']) ?></td>
          <td><?= e($r['service_no']) ?></td>
          <td><?= e($r['branch_name']) ?></td>
          <td><?= e($r['leave_type']) ?></td>
          <td><?= e($r['start_date']) ?></td>
          <td><?= e($r['end_date']) ?></td>
          <td><?= e($r['destination'] ?? '') ?></td>
          <td><?= e($r['reason'] ?? '') ?></td>
          <td><?= e($r['status']) ?></td>
          <td><?= e($r['submitter'] ?? '') ?></td>
          <td><?= e($r['submitted_at']) ?></td>
          <td><?= e($r['mgr_name'] ?? '') ?></td>
          <td><?= e($r['adm_name'] ?? '') ?></td>
        </tr>
      <?php endforeach; endif; ?>
    </tbody>
  </table>

  <div class="no-print">
    <button onclick="window.print()" style="padding:8px 16px;background:#0d1629;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
  </div>
</body>
</html>

