<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_login();
$pdo = db();

$type = $_GET['type'] ?? 'csv';
$date = $_GET['date'] ?? date('Y-m-d');
$branchId = user_branch_filter($user);
if ($user['role']==='admin' && !empty($_GET['branch'])) $branchId = (int)$_GET['branch'];

$summaries = branch_summary($pdo, $date, $branchId);

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="UPF_MDD_Report_' . $date . '.csv"');
    $out = fopen('php://output', 'w');
    fputcsv($out, [APP_ORG]);
    fputcsv($out, [APP_NAME]);
    fputcsv($out, ['Attendance Report — ' . date('j F Y', strtotime($date))]);
    fputcsv($out, ['Generated by: ' . $user['full_name'] . ' on ' . date('Y-m-d H:i')]);
    fputcsv($out, []);
    fputcsv($out, ['Branch','Location','Total','Present','AWOL','Leave','Sick','Unrecorded','Attendance %']);
    foreach ($summaries as $s) {
        fputcsv($out, [$s['branch_name'], $s['location'], $s['total'], $s['present'], $s['awol'], $s['on_leave'], $s['sick'], $s['unrecorded'], $s['total']?round(($s['present']/$s['total'])*100).'%':'0%']);
    }
    fclose($out); exit;
}

// Print/PDF: a printable HTML page
$logoData = base64_encode(file_get_contents(BASE_PATH . '/public/assets/logo.jpg'));
?><!doctype html>
<html><head><meta charset="utf-8"><title>UPF MDD Report — <?= e($date) ?></title>
<style>
body{font-family:Arial,sans-serif;color:#1a2236;margin:30px}
.head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #d4a017;padding-bottom:12px;margin-bottom:18px}
.head img{width:70px;height:70px;border-radius:50%;border:2px solid #d4a017}
.head .org{font-weight:700;letter-spacing:1px;color:#0d1629}
.head .sys{font-size:13px;color:#475569}
.head .motto{font-size:11px;font-style:italic;letter-spacing:2px;color:#64748b}
table{width:100%;border-collapse:collapse;margin-top:14px}
th,td{border:1px solid #cbd5e1;padding:8px 10px;font-size:12px;text-align:left}
th{background:#0d1629;color:#fff}
tr.total{background:#f1f5f9;font-weight:700}
.meta{color:#64748b;font-size:12px;margin-bottom:10px}
@media print { .no-print{display:none} }
</style></head>
<body>
<div class="head">
  <img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF">
  <div>
    <div class="org"><?= e(APP_ORG) ?></div>
    <div class="sys"><?= e(APP_NAME) ?></div>
    <div class="motto"><?= e(APP_MOTTO) ?></div>
  </div>
</div>
<h2 style="margin:0">Attendance Report — <?= e(date('j F Y', strtotime($date))) ?></h2>
<div class="meta">Generated by <?= e($user['full_name']) ?> on <?= date('j F Y H:i') ?></div>
<table>
  <thead><tr><th>Branch</th><th>Location</th><th>Total</th><th>Present</th><th>AWOL</th><th>Leave</th><th>Sick</th><th>Unrecorded</th><th>Attendance %</th></tr></thead>
  <tbody>
  <?php $tot=['total'=>0,'present'=>0,'awol'=>0,'on_leave'=>0,'sick'=>0,'unrecorded'=>0];
  foreach ($summaries as $s): foreach ($tot as $k=>$_) $tot[$k]+=$s[$k]; ?>
    <tr><td><?= e($s['branch_name']) ?></td><td><?= e($s['location']) ?></td>
      <td><?= $s['total'] ?></td><td><?= $s['present'] ?></td><td><?= $s['awol'] ?></td>
      <td><?= $s['on_leave'] ?></td><td><?= $s['sick'] ?></td><td><?= $s['unrecorded'] ?></td>
      <td><?= $s['total']?round(($s['present']/$s['total'])*100):0 ?>%</td></tr>
  <?php endforeach; ?>
    <tr class="total"><td colspan="2">TOTAL</td><td><?= $tot['total'] ?></td><td><?= $tot['present'] ?></td><td><?= $tot['awol'] ?></td>
      <td><?= $tot['on_leave'] ?></td><td><?= $tot['sick'] ?></td><td><?= $tot['unrecorded'] ?></td>
      <td><?= $tot['total']?round(($tot['present']/$tot['total'])*100):0 ?>%</td></tr>
  </tbody>
</table>
<div class="no-print" style="margin-top:18px">
  <button onclick="window.print()" style="padding:8px 16px;background:#0d1629;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
</div>
</body></html>
