<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../includes/db.php';

$user = require_login();
$pdo = db();

$type = $_GET['type'] ?? 'csv'; // csv | html
$status = $_GET['status'] ?? 'present';
if (!in_array($status, ['present','awol','leave','onleave','sick','unrecorded'], true)) $status = 'present';

$date = $_GET['date'] ?? date('Y-m-d');
$branchId = user_branch_filter($user);
if ($user['role']==='admin' && !empty($_GET['branch'])) $branchId = (int)$_GET['branch'];

$where = '1=1';
$params = [':d' => $date];
if ($branchId !== null) {
    $where .= ' AND e.branch_id = :b';
    $params[':b'] = $branchId;
}

if ($status === 'unrecorded') {
    $where .= ' AND ds.status IS NULL';
} else {
    if ($status === 'onleave' || $status === 'leave') {
        $where .= " AND (
            ds.status = 'onleave' OR
            EXISTS (
                SELECT 1 FROM leave_requests lr
                WHERE lr.employee_id = e.id
                  AND lr.status='approved'
                  AND lr.start_date <= :d
                  AND lr.end_date >= :d
                  AND lr.destination IS NOT NULL
            )
        )";
    } else {
        $where .= ' AND ds.status = :s';
        $params[':s'] = $status;
    }
}

// Reuse the same columns as status-details.php
$sql = "SELECT e.*, b.name AS branch_name, ds.status, ds.notes
        FROM employees e
        JOIN branches b ON b.id = e.branch_id
        LEFT JOIN daily_status ds ON ds.employee_id = e.id AND ds.date = :d
        LEFT JOIN leave_requests lr ON lr.employee_id = e.id
             AND lr.status='approved'
             AND lr.start_date <= :d
             AND lr.end_date >= :d
        WHERE $where AND e.active = 1
        ORDER BY b.name, e.full_name";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$rows = $stmt->fetchAll();

$effectiveStatusLabel = status_label($status === 'leave' ? 'onleave' : $status);
$baseName = 'UPF_MDD_' . preg_replace('/[^A-Za-z0-9_-]+/', '_', (string)$effectiveStatusLabel) . '_Details_' . $date;

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $baseName . '.csv"');
    $out = fopen('php://output', 'w');

    fputcsv($out, [APP_ORG]);
    fputcsv($out, [APP_NAME]);
    fputcsv($out, ['Status Details Export — ' . $effectiveStatusLabel]);
    fputcsv($out, ['Generated by: ' . ($user['full_name'] ?? 'user') . ' on ' . date('Y-m-d H:i')]);
    fputcsv($out, []);

    fputcsv($out, ['Date', 'Force/File No','Name','Rank','Gender','Branch','Phone','Status','Leave Destination','Leave Start Date','Leave End Date','Leave Duration (Days)','Notes']);

    foreach ($rows as $r) {
        // Destination is computed (same as status-details.php)
        $dest = '';
        $leaveStart = '';
        $leaveEnd = '';
        $daysOnLeave = '';
        $computedOnLeave = false;

        if ($status === 'onleave' || $status === 'leave') {
            $computedOnLeave = true;
            $dStmt = $pdo->prepare("SELECT destination, start_date, end_date FROM leave_requests
                WHERE employee_id=? AND status='approved'
                  AND start_date <= :d AND end_date >= :d
                ORDER BY submitted_at DESC LIMIT 1");
            $dStmt->execute([(int)$r['id'], ':d' => $date]);
            $rowDest = $dStmt->fetch();
            $dest = $rowDest['destination'] ?? '';
            $leaveStart = $rowDest['start_date'] ?? '';
            $leaveEnd = $rowDest['end_date'] ?? '';

            if (!empty($leaveStart) && !empty($leaveEnd)) {
                try {
                    $ds = new DateTimeImmutable($leaveStart);
                    $de = new DateTimeImmutable($leaveEnd);
                    $diff = $ds->diff($de);
                    $daysOnLeave = (string)($diff->days + 1); // inclusive
                } catch (Throwable $t) {
                    $daysOnLeave = '';
                }
            }
        }

        $statusOut = '';
        if ($computedOnLeave) {
            $statusOut = 'onleave';
        } else {
            $statusOut = $r['status'] ? (string)$r['status'] : 'unrecorded';
        }

        fputcsv($out, [
            $date,
            $r['service_no'],
            $r['full_name'],
            $r['rank'],
            $r['gender'] === 'M' ? 'Male' : 'Female',
            $r['branch_name'],
            $r['phone'],
            $statusOut,
            $dest,
            $leaveStart,
            $leaveEnd,
            $daysOnLeave,
            $r['notes'] ?? ''
        ]);
    }

    fclose($out);
    exit;
}

// Print/PDF
$logoPath = BASE_PATH . '/public/assets/logo.jpg';
$logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : '';
?>
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title><?= e('UPF MDD — ' . $effectiveStatusLabel . ' — ' . $date) ?></title>
  <style>
    body{font-family:Arial,sans-serif;color:#1a2236;margin:30px}
    .head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #d4a017;padding-bottom:12px;margin-bottom:18px}
    .head img{width:70px;height:70px;border-radius:50%;border:2px solid #d4a017}
    .org{font-weight:700;letter-spacing:1px;color:#0d1629}
    .sys{font-size:13px;color:#475569}
    table{width:100%;border-collapse:collapse;margin-top:14px}
    th,td{border:1px solid #cbd5e1;padding:8px 10px;font-size:12px;text-align:left;vertical-align:top}
    th{background:#0d1629;color:#fff}
    .meta{color:#64748b;font-size:12px;margin-bottom:10px}
    .no-print{margin-top:18px}
    @media print { .no-print{display:none} }
  </style>
</head>
<body>
  <div class="head">
    <?php if ($logoData): ?><img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF"><?php endif; ?>
    <div>
      <div class="org"><?= e(APP_ORG) ?></div>
      <div class="sys"><?= e(APP_NAME) ?></div>
      <div class="motto"><?= e(APP_MOTTO) ?></div>
    </div>
  </div>

  <h2 style="margin:0"><?= e($effectiveStatusLabel) ?> — <?= e(date('j F Y', strtotime($date))) ?></h2>
  <div class="meta">Generated by <?= e($user['full_name'] ?? 'user') ?> on <?= date('j F Y H:i') ?></div>

  <table>
    <thead>
      <tr>
        <th>Force/File No</th><th>Name</th><th>Rank</th><th>Gender</th><th>Branch</th><th>Phone</th><th>Status</th><th>Leave Destination</th><th>Leave Start</th><th>Leave End</th><th>Leave Duration (Days)</th><th>Notes</th>
      </tr>
    </thead>
    <tbody>
      <?php if (!$rows): ?>
        <tr><td colspan="9" style="text-align:center;color:#64748b">No records found.</td></tr>
      <?php else: foreach ($rows as $r): ?>
        <?php
          $dest = '';
          $leaveStart = '';
          $leaveEnd = '';
          $daysOnLeave = '';
          $computedOnLeave = ($status === 'onleave' || $status === 'leave');
          if ($computedOnLeave) {
              $dStmt = $pdo->prepare("SELECT destination, start_date, end_date FROM leave_requests
                  WHERE employee_id=? AND status='approved'
                    AND start_date <= :d AND end_date >= :d
                  ORDER BY submitted_at DESC LIMIT 1");
              $dStmt->execute([(int)$r['id'], ':d' => $date]);
              $rowDest = $dStmt->fetch();
              $dest = $rowDest['destination'] ?? '';
              $leaveStart = $rowDest['start_date'] ?? '';
              $leaveEnd = $rowDest['end_date'] ?? '';
              if (!empty($leaveStart) && !empty($leaveEnd)) {
                  try {
                      $ds = new DateTimeImmutable($leaveStart);
                      $de = new DateTimeImmutable($leaveEnd);
                      $diff = $ds->diff($de);
                      $daysOnLeave = (string)($diff->days + 1);
                  } catch (Throwable $t) {
                      $daysOnLeave = '';
                  }
              }
          }
          $statusOut = $computedOnLeave ? 'onleave' : ($r['status'] ? (string)$r['status'] : 'unrecorded');
        ?>
        <tr>
          <td><?= e($r['service_no']) ?></td>
          <td><?= e($r['full_name']) ?></td>
          <td><?= e($r['rank']) ?></td>
          <td><?= e($r['gender'] === 'M' ? 'Male' : 'Female') ?></td>
          <td><?= e($r['branch_name']) ?></td>
          <td><?= e($r['phone']) ?></td>
          <td><?= e($statusOut) ?></td>
          <td><?= e($dest) ?></td>
          <td><?= e($leaveStart) ?></td>
          <td><?= e($leaveEnd) ?></td>
          <td><?= $daysOnLeave !== '' ? e($daysOnLeave) : '&mdash;' ?></td>
          <td><?= e($r['notes'] ?? '') ?></td>
        </tr>
      <?php endforeach; endif; ?>
    </tbody>
  </table>

  <div class="no-print">
    <button onclick="window.print()" style="padding:8px 16px;background:#0d1629;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
  </div>
</body>
</html>

