<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/audit.php';

$user = require_role(['admin','manager']);
$pdo = db();

$type = $_GET['type'] ?? 'csv'; // csv | html
$q = trim((string)($_GET['q'] ?? ''));
$branchId = $_GET['branch'] ?? null;

// Managers only export their own branch scope
$scopedBranchId = null;
if (is_manager($user)) {
    $scopedBranchId = (int)$user['branch_id'];
} elseif (!empty($branchId)) {
    $scopedBranchId = (int)$branchId;
}

$allowedCols = [
    'service_no' => 'Force/File No',
    'full_name' => 'Name',
    'rank' => 'Rank',
    'gender' => 'Gender',
    'branch_name' => 'Branch',
    'phone' => 'Phone',
    'email' => 'Email'
];

$colsParam = (string)($_GET['cols'] ?? '');
$requested = array_filter(array_map('trim', $colsParam === '' ? [] : explode(',', $colsParam)));
$cols = [];
foreach ($requested as $c) {
    if (isset($allowedCols[$c])) $cols[$c] = $allowedCols[$c];
}
if (empty($cols)) {
    // default columns
    $cols = [
        'service_no' => $allowedCols['service_no'],
        'full_name' => $allowedCols['full_name'],
        'rank' => $allowedCols['rank'],
        'gender' => $allowedCols['gender'],
        'branch_name' => $allowedCols['branch_name'],
        'phone' => $allowedCols['phone'],
        'email' => $allowedCols['email']
    ];
}

$where = '1=1';
$params = [];
if ($scopedBranchId !== null) {
    $where .= ' AND e.branch_id = :b';
    $params[':b'] = $scopedBranchId;
}
if ($q !== '') {
    $where .= ' AND (e.full_name LIKE :q OR e.service_no LIKE :q2)';
    $params[':q'] = '%' . $q . '%';
    $params[':q2'] = '%' . $q . '%';
}

// Pull branch name always (export will choose which columns)
$sql = "SELECT e.*, b.name AS branch_name
        FROM employees e
        JOIN branches b ON b.id=e.branch_id
        WHERE $where AND e.active=1
        ORDER BY e.full_name";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$rows = $stmt->fetchAll();

// Export file base name
$labelParts = [];
if ($scopedBranchId !== null) {
    $labelParts[] = 'Branch_' . $scopedBranchId;
}
if ($q !== '') $labelParts[] = 'Search_' . preg_replace('/[^A-Za-z0-9_-]+/', '_', $q);
$label = !empty($labelParts) ? implode('_', $labelParts) : 'All';
$baseName = 'UPF_MDD_Personnel_Export_' . $label . '_' . date('Y-m-d');

audit_log($user, 'export_personnel', 'employees', null, ['cols' => array_keys($cols)]);

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $baseName . '.csv"');
    $out = fopen('php://output', 'w');

    fputcsv($out, [APP_ORG]);
    fputcsv($out, [APP_NAME]);
    fputcsv($out, ['Personnel Export']);
    fputcsv($out, ['Generated by: ' . ($user['full_name'] ?? 'user') . ' on ' . date('Y-m-d H:i')]);
    fputcsv($out, []);

    fputcsv($out, array_values($cols));

    foreach ($rows as $r) {
        $line = [];
        foreach (array_keys($cols) as $key) {
            if ($key === 'gender') {
                $line[] = ($r['gender'] ?? '') === 'F' ? 'Female' : 'Male';
            } else {
                $line[] = $r[$key] ?? '';
            }
        }
        fputcsv($out, $line);
    }

    fclose($out);
    exit;
}

// Print/PDF: printable HTML
$logoPath = BASE_PATH . '/public/assets/logo.jpg';
$logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : '';
$colHeaders = array_values($cols);
$colKeys = array_keys($cols);
?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title><?= e('UPF MDD — Personnel Export — ' . $label) ?></title>
    <style>
        body{font-family:Arial,sans-serif;color:#1a2236;margin:30px}
        .head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #d4a017;padding-bottom:12px;margin-bottom:18px}
        .head img{width:70px;height:70px;border-radius:50%;border:2px solid #d4a017}
        .org{font-weight:700;letter-spacing:1px;color:#0d1629}
        .sys{font-size:13px;color:#475569}
        table{width:100%;border-collapse:collapse;margin-top:14px}
        th,td{border:1px solid #cbd5e1;padding:8px 10px;font-size:12px;text-align:left;vertical-align:top}
        th{background:#0d1629;color:#fff}
        .meta{color:#64748b;font-size:12px;margin-bottom:10px}
        .no-print{margin-top:18px}
        @media print { .no-print{display:none} }
    </style>
</head>
<body>
<div class="head">
    <?php if ($logoData): ?><img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF"><?php endif; ?>
    <div>
        <div class="org"><?= e(APP_ORG) ?></div>
        <div class="sys"><?= e(APP_NAME) ?></div>
        <div class="motto"><?= e(APP_MOTTO) ?></div>
    </div>
</div>
<h2 style="margin:0">Personnel Export — <?= e($label) ?></h2>
<div class="meta">Generated by <?= e($user['full_name'] ?? 'user') ?> on <?= date('j F Y H:i') ?></div>

<table>
    <thead><tr>
        <?php foreach ($colHeaders as $h): ?>
            <th><?= e($h) ?></th>
        <?php endforeach; ?>
    </tr></thead>
    <tbody>
        <?php if (empty($rows)): ?>
            <tr><td colspan="<?= count($colHeaders) ?>" style="text-align:center;color:#64748b">No personnel found.</td></tr>
        <?php else: foreach ($rows as $r): ?>
            <tr>
                <?php foreach ($colKeys as $key): ?>
                    <td>
                        <?= e(
                            $key === 'gender'
                                ? ((($r['gender'] ?? '') === 'F') ? 'Female' : 'Male')
                                : ($r[$key] ?? '')
                        ) ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; endif; ?>
    </tbody>
</table>

<div class="no-print">
    <button onclick="window.print()" style="padding:8px 16px;background:#0d1629;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
</div>
</body>
</html>

