<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
require_once __DIR__ . '/../includes/notifications.php';
require_once __DIR__ . '/../includes/audit.php';

$user = require_login();
$pdo = db();

$type = $_GET['type'] ?? 'csv'; // csv | html
$status = $_GET['status'] ?? '';

$where = '1=1';
$params = [];
if (is_manager($user)) {
    // Managers only export their own branch scope
    $where .= ' AND (r.branch_id = ? OR r.branch_id IS NULL)';
    $params[] = $user['branch_id'];
}
if (!empty($status) && in_array($status, ['pending_manager','pending_admin','approved','rejected'], true)) {
    $where .= ' AND r.status = ?';
    $params[] = $status;
}

$stmt = $pdo->prepare("SELECT r.*, u.full_name AS generator, b.name AS branch_name, rv.full_name AS reviewer
    FROM reports r
    LEFT JOIN users u ON u.id=r.generated_by
    LEFT JOIN branches b ON b.id=r.branch_id
    LEFT JOIN users rv ON rv.id=r.reviewed_by
    WHERE $where
    ORDER BY
      CASE r.status WHEN 'pending_manager' THEN 1 WHEN 'pending_admin' THEN 2 WHEN 'approved' THEN 3 ELSE 4 END,
      r.generated_at DESC LIMIT 200");
$stmt->execute($params);
$reports = $stmt->fetchAll();

$baseName = 'UPF_MDD_Report_History_' . date('Y-m-d');

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $baseName . '.csv"');
    $out = fopen('php://output', 'w');

    fputcsv($out, [APP_ORG]);
    fputcsv($out, [APP_NAME]);
    fputcsv($out, ['Report History Export']);
    fputcsv($out, ['Generated by: ' . ($user['full_name'] ?? $user['username'] ?? 'user') . ' on ' . date('Y-m-d H:i')]);
    fputcsv($out, []);

    fputcsv($out, ['Date','Branch','Status','Generated By','Generated At','Reviewed By','Reviewed At','Review Notes','Report ID']);
    foreach ($reports as $r) {
        fputcsv($out, [
            date('Y-m-d', strtotime($r['date'])),
            $r['branch_name'] ?? '',
            $r['status'] ?? '',
            $r['generator'] ?? '',
            $r['generated_at'] ?? '',
            $r['reviewer'] ?? '',
            $r['reviewed_at'] ?? '',
            $r['review_notes'] ?? '',
            (int)$r['id']
        ]);
    }
    fclose($out);
    exit;
}

// Print/PDF: printable HTML
$logoPath = BASE_PATH . '/public/assets/logo.jpg';
$logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : '';
?>
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title><?= e('UPF MDD Report History — ' . date('j F Y')) ?></title>
  <style>
    body{font-family:Arial,sans-serif;color:#1a2236;margin:30px}
    .head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #d4a017;padding-bottom:12px;margin-bottom:18px}
    .head img{width:70px;height:70px;border-radius:50%;border:2px solid #d4a017}
    .org{font-weight:700;letter-spacing:1px;color:#0d1629}
    .sys{font-size:13px;color:#475569}
    table{width:100%;border-collapse:collapse;margin-top:14px}
    th,td{border:1px solid #cbd5e1;padding:8px 10px;font-size:12px;text-align:left;vertical-align:top}
    th{background:#0d1629;color:#fff}
    .meta{color:#64748b;font-size:12px;margin-bottom:10px}
    .no-print{margin-top:18px}
    @media print { .no-print{display:none} }
  </style>
</head>
<body>
  <div class="head">
    <?php if ($logoData): ?><img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF"><?php endif; ?>
    <div>
      <div class="org"><?= e(APP_ORG) ?></div>
      <div class="sys"><?= e(APP_NAME) ?></div>
      <div class="motto"><?= e(APP_MOTTO) ?></div>
    </div>
  </div>

  <h2 style="margin:0">Report History Export</h2>
  <div class="meta">Generated by <?= e($user['full_name'] ?? 'user') ?> on <?= date('j F Y H:i') ?></div>
  <?php if (!empty($status)): ?><div class="meta">Status filter: <?= e($status) ?></div><?php endif; ?>

  <table>
    <thead>
      <tr>
        <th>Date</th><th>Branch</th><th>Status</th><th>Generated By</th><th>Generated At</th><th>Reviewed By</th><th>Reviewed At</th><th>Review Notes</th><th>Report ID</th>
      </tr>
    </thead>
    <tbody>
      <?php if (!$reports): ?>
        <tr><td colspan="9" style="text-align:center;color:#64748b">No reports found.</td></tr>
      <?php else: foreach ($reports as $r): ?>
        <tr>
          <td><?= e(date('j M Y', strtotime($r['date'] ?? 'now'))) ?></td>
          <td><?= e($r['branch_name'] ?? 'All Branches') ?></td>
          <td><?= e($r['status'] ?? '') ?></td>
          <td><?= e($r['generator'] ?? '—') ?></td>
          <td><?= e($r['generated_at'] ?? '—') ?></td>
          <td><?= e($r['reviewer'] ?? '—') ?></td>
          <td><?= e($r['reviewed_at'] ?? '—') ?></td>
          <td><?= e($r['review_notes'] ?? '') ?></td>
          <td><?= (int)$r['id'] ?></td>
        </tr>
      <?php endforeach; endif; ?>
    </tbody>
  </table>

  <div class="no-print">
    <button onclick="window.print()" style="padding:8px 16px;background:#0d1629;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
  </div>
</body>
</html>

