<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_login();
$page = 'history';
$page_title = 'History';
$pdo = db();

$where = '1=1'; $params = [];
if ($user['role']==='manager') { $where .= ' AND (r.branch_id = ? OR r.branch_id IS NULL)'; $params[] = $user['branch_id']; }

$stmt = $pdo->prepare("SELECT r.*, u.full_name AS generator, b.name AS branch_name FROM reports r LEFT JOIN users u ON u.id=r.generated_by LEFT JOIN branches b ON b.id=r.branch_id WHERE $where ORDER BY r.generated_at DESC LIMIT 200");
$stmt->execute($params);
$reports = $stmt->fetchAll();

$detail = null;
if (!empty($_GET['id'])) {
    $s = $pdo->prepare("SELECT r.*, u.full_name AS generator, b.name AS branch_name FROM reports r LEFT JOIN users u ON u.id=r.generated_by LEFT JOIN branches b ON b.id=r.branch_id WHERE r.id=?");
    $s->execute([(int)$_GET['id']]);
    $detail = $s->fetch();
    if ($detail) $detail['summary'] = json_decode($detail['summary_json'], true) ?: [];
}

include __DIR__ . '/../includes/header.php';
?>
<div class="page-header"><div><h1>Report History</h1><div class="desc">Previously generated attendance reports</div></div></div>

<div class="card">
  <div class="table-wrap">
    <table>
      <thead><tr><th>Date</th><th>Branch</th><th>Generated By</th><th>Generated At</th><th></th></tr></thead>
      <tbody>
        <?php foreach ($reports as $r): ?>
          <tr>
            <td><?= e(date('j F Y', strtotime($r['date']))) ?></td>
            <td><?= e($r['branch_name'] ?: 'All Branches') ?></td>
            <td><?= e($r['generator'] ?? '—') ?></td>
            <td><?= e(date('Y-m-d H:i', strtotime($r['generated_at']))) ?></td>
            <td><a class="btn btn-sm btn-secondary" href="/history.php?id=<?= $r['id'] ?>">View</a></td>
          </tr>
        <?php endforeach; ?>
        <?php if (!$reports): ?><tr><td colspan="5" style="text-align:center;color:var(--muted);padding:24px">No reports yet. Generate one from the Reports page.</td></tr><?php endif; ?>
      </tbody>
    </table>
  </div>
</div>

<?php if ($detail): ?>
<div class="card">
  <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px">
    <h3 style="margin:0">Report Detail — <?= e(date('j F Y', strtotime($detail['date']))) ?></h3>
    <a class="btn btn-secondary" href="/history.php">Close</a>
  </div>
  <div class="muted" style="margin:6px 0 14px">Generated by <?= e($detail['generator']) ?> on <?= e(date('Y-m-d H:i', strtotime($detail['generated_at']))) ?></div>
  <div class="table-wrap">
    <table>
      <thead><tr><th>Branch</th><th>Total</th><th>Present</th><th>AWOL</th><th>Leave</th><th>Sick</th><th>Unrecorded</th></tr></thead>
      <tbody>
        <?php foreach ($detail['summary'] as $s): ?>
          <tr><td><?= e($s['branch_name']) ?></td><td><?= $s['total'] ?></td><td><?= $s['present'] ?></td>
            <td><?= $s['awol'] ?></td><td><?= $s['on_leave'] ?></td><td><?= $s['sick'] ?></td><td><?= $s['unrecorded'] ?></td></tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
<?php endif; ?>
<?php include __DIR__ . '/../includes/footer.php'; ?>
